// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spkwiylihicfnwjqkgub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwa3dpeWxpaGljZm53anFrZ3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzUwNDYsImV4cCI6MjA2ODAxMTA0Nn0.ryEbbCkdT6YS0nGXJRB10Z47biHputRy3RRGvd4sNBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});